describe("e2e", function(){
    it("letsgo", function(){
        cy.visit("http://localhost:4200/")
        cy.wait(1500)
        cy.contains("EN").click()
        cy.wait(1500)
        cy.contains("РУС").click()
        cy.wait(1500)
        cy.contains("Список заданий").click()
        cy.wait(1500)
        cy.contains("EN").click()
        cy.wait(1500)
        cy.contains("РУС").click()
        cy.contains("Редактировать").click()
        cy.wait(1500)
        cy.get('input[id="noteTb"]').type('test note')
        cy.wait(1500)
        cy.contains("Редактировать").click()
        cy.wait(1500)
        cy.contains("Редактировать").click()
        cy.wait(1500)
        cy.contains("Список заданий").click()
        cy.wait(1500)
        cy.contains("Добавить задание").click()
        cy.wait(1500)
        cy.contains("EN").click()
        cy.wait(1500)
        cy.contains("РУС").click()
        cy.wait(1500)
        cy.get('input[id="idTb"]').type('11111')
        cy.get('input[id="dateTb"]').type('11.11.2222')
        cy.get('input[id="noteTb"]').type('add test note')
        cy.wait(1500)
        cy.get('button[class="btn"]').click()
        cy.wait(1500)
        cy.contains("Список заданий").click()
        cy.wait(1500)
        cy.contains("Удалить").click()
        cy.wait(1500)
        cy.contains("Об авторе").click()
        cy.wait(1500)
        cy.contains("EN").click()
        cy.wait(1500)
        cy.contains("РУС").click()
    })
})